#!/usr/bin/env python3
"""Sudoku puzzle bank generator (#616).

Dev-time tool. Writes ``frontend/src/game/sudoku/puzzles.json``:

    {
      "easy":   ["<81 chars>", ...],   # 1000 puzzles, 36-44 clues
      "medium": [...],                  # 1000 puzzles, 28-35 clues
      "hard":   [...]                   # 1000 puzzles, 22-27 clues
    }

Solvability guarantee
---------------------
Each puzzle is generated by starting from a valid complete grid and
removing one cell at a time. Before a removal is accepted, a uniqueness
-checking solver (backtracking, early-exit at the 2nd solution found)
confirms exactly one solution remains. Removals that would create a
second solution are rejected and the cell is restored. This makes it
mathematically impossible for this script to emit an ambiguous puzzle.

Difficulty classification is by clue count (the Sudoku community's
rough-but-reasonable proxy). Technique-based verification (naked singles
only for Easy, X-Wing etc. for Hard) is a follow-up — tracked in the
QA release issue.

Usage
-----
    python backend/scripts/gen_sudoku_puzzles.py \\
        --count 1000 \\
        --output frontend/src/game/sudoku/puzzles.json
"""

from __future__ import annotations

import argparse
import json
import random
import sys
import time
from pathlib import Path

# ---------------------------------------------------------------------------
# Grid representation
# ---------------------------------------------------------------------------
# Flat list of 81 ints; 0 = empty, 1-9 = digit.

N = 9
BOX_ROW = [r // 3 for r in range(N)]
BOX_COL = [c // 3 for c in range(N)]

# Pre-computed peer lists: peers[i] is the set of indices that share a
# row, column, or box with i (excluding i itself).
_PEERS: list[frozenset[int]] = []
for i in range(81):
    r, c = divmod(i, 9)
    br, bc = BOX_ROW[r], BOX_COL[c]
    peers: set[int] = set()
    for j in range(81):
        if j == i:
            continue
        jr, jc = divmod(j, 9)
        if jr == r or jc == c or (BOX_ROW[jr] == br and BOX_COL[jc] == bc):
            peers.add(j)
    _PEERS.append(frozenset(peers))


def _candidates(grid: list[int], i: int) -> int:
    """Return a 9-bit mask of digits not conflicting with peers of cell ``i``."""
    used = 0
    for p in _PEERS[i]:
        v = grid[p]
        if v:
            used |= 1 << (v - 1)
    return (~used) & 0x1FF


def _pick_empty(grid: list[int]) -> tuple[int, int]:
    """Return (index, candidate_mask) for the empty cell with fewest
    candidates.  Returns (-1, 0) when the grid is full.  (MRV heuristic.)"""
    best_i = -1
    best_mask = 0
    best_count = 10
    for i in range(81):
        if grid[i] == 0:
            mask = _candidates(grid, i)
            cnt = bin(mask).count("1")
            if cnt < best_count:
                best_count = cnt
                best_i = i
                best_mask = mask
                if cnt <= 1:
                    break
    return best_i, best_mask


# ---------------------------------------------------------------------------
# Solver with early-exit solution counter
# ---------------------------------------------------------------------------


def count_solutions(grid: list[int], limit: int = 2) -> int:
    """Count solutions up to ``limit``.  Returns 0, 1, or ``limit`` (stops
    exploring once ``limit`` solutions have been found).

    Used two ways:
    - ``count_solutions(g, 2)`` during hollowing — a cell removal is only
      accepted if the count returns to exactly 1.
    - ``count_solutions(g, 2)`` during the final audit — every emitted
      puzzle must still count exactly 1.
    """
    counter = [0]
    work = list(grid)  # private working copy

    def recurse() -> None:
        if counter[0] >= limit:
            return
        i, mask = _pick_empty(work)
        if i == -1:
            counter[0] += 1
            return
        while mask:
            lsb = mask & -mask
            mask ^= lsb
            d = lsb.bit_length()
            work[i] = d
            recurse()
            work[i] = 0
            if counter[0] >= limit:
                return

    recurse()
    return counter[0]


def solve(grid: list[int]) -> list[int] | None:
    """Return a solved copy of ``grid``, or None if unsolvable."""
    work = list(grid)

    def recurse() -> bool:
        i, mask = _pick_empty(work)
        if i == -1:
            return True
        while mask:
            lsb = mask & -mask
            mask ^= lsb
            d = lsb.bit_length()
            work[i] = d
            if recurse():
                return True
            work[i] = 0
        return False

    return work if recurse() else None


# ---------------------------------------------------------------------------
# Full grid generator
# ---------------------------------------------------------------------------


def random_full_grid(rng: random.Random) -> list[int]:
    """Return a random complete valid grid."""
    grid = [0] * 81

    def recurse() -> bool:
        i, mask = _pick_empty(grid)
        if i == -1:
            return True
        digits = []
        m = mask
        while m:
            lsb = m & -m
            m ^= lsb
            digits.append(lsb.bit_length())
        rng.shuffle(digits)
        for d in digits:
            grid[i] = d
            if recurse():
                return True
            grid[i] = 0
        return False

    recurse()
    return grid


# ---------------------------------------------------------------------------
# Hollowing (the uniqueness-preserving removal loop)
# ---------------------------------------------------------------------------

TIER_RANGES = {
    "easy": (36, 44),
    "medium": (28, 35),
    "hard": (22, 27),
}


def hollow(grid: list[int], target_clues: int, rng: random.Random) -> list[int] | None:
    """Remove cells from ``grid`` one at a time, keeping only those
    removals that preserve a unique solution, until the count drops to
    ``target_clues`` clues (or no further removals possible).

    Returns the hollowed grid, or None if we couldn't reach within the
    acceptable range.
    """
    puzzle = list(grid)
    order = list(range(81))
    rng.shuffle(order)
    current_clues = 81

    for idx in order:
        if current_clues <= target_clues:
            break
        saved = puzzle[idx]
        if saved == 0:
            continue
        puzzle[idx] = 0
        if count_solutions(puzzle, 2) == 1:
            current_clues -= 1
        else:
            puzzle[idx] = saved

    return puzzle


def classify(puzzle: list[int]) -> str | None:
    """Assign a puzzle to a tier based on its clue count, or None if it
    doesn't land in any configured tier."""
    clues = sum(1 for v in puzzle if v)
    for tier, (lo, hi) in TIER_RANGES.items():
        if lo <= clues <= hi:
            return tier
    return None


def puzzle_to_string(puzzle: list[int]) -> str:
    return "".join(str(v) for v in puzzle)


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------


def generate_bank(count_per_tier: int, seed: int = 20260419) -> dict[str, list[str]]:
    rng = random.Random(seed)
    banks: dict[str, list[str]] = {"easy": [], "medium": [], "hard": []}
    start = time.monotonic()
    attempts = 0

    # Interleave: target the currently-shortest tier first.  Each "hard"
    # generation attempt is the slowest path but also the most likely to
    # yield a hard puzzle (low clue count).  Easy/medium tiers are
    # seeded by generating with their tier's target and keeping any
    # by-product that drops into another tier along the way.
    while min(len(b) for b in banks.values()) < count_per_tier:
        attempts += 1
        grid = random_full_grid(rng)

        # Pick target based on which tier is most under-filled.
        need = {t: count_per_tier - len(banks[t]) for t in banks}
        tier = max(need, key=lambda t: need[t])
        lo, hi = TIER_RANGES[tier]
        target = rng.randint(lo, hi)

        puzzle = hollow(grid, target, rng)
        if puzzle is None:
            continue
        resolved = classify(puzzle)
        if resolved is None:
            continue
        if len(banks[resolved]) >= count_per_tier:
            continue

        banks[resolved].append(puzzle_to_string(puzzle))

        if attempts % 25 == 0:
            elapsed = time.monotonic() - start
            sizes = {t: len(banks[t]) for t in banks}
            total = sum(sizes.values())
            rate = total / elapsed if elapsed else 0
            print(
                f"[{elapsed:6.1f}s] attempts={attempts} sizes={sizes} rate={rate:.2f}/s",
                file=sys.stderr,
            )

    elapsed = time.monotonic() - start
    print(
        f"Done. attempts={attempts} elapsed={elapsed:.1f}s sizes="
        f"{ {t: len(b) for t, b in banks.items()} }",
        file=sys.stderr,
    )
    return banks


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate Sudoku puzzle bank.")
    ap.add_argument("--count", type=int, default=1000, help="puzzles per difficulty")
    ap.add_argument("--seed", type=int, default=20260419)
    ap.add_argument(
        "--output",
        default=str(
            Path(__file__).resolve().parents[2]
            / "frontend"
            / "src"
            / "game"
            / "sudoku"
            / "puzzles.json"
        ),
    )
    args = ap.parse_args()

    banks = generate_bank(args.count, args.seed)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(banks, indent=2) + "\n")
    print(f"Wrote {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
