#!/usr/bin/env python3
"""Sudoku puzzle bank generator (#616, #748).

Dev-time tool. Writes ``frontend/src/game/sudoku/puzzles.json`` (classic
9×9) or ``frontend/src/game/sudoku/puzzles_mini.json`` (mini 6×6):

    {
      "easy":   ["<N² chars>", ...],
      "medium": [...],
      "hard":   [...]
    }

Solvability guarantee
---------------------
Each puzzle is generated by starting from a valid complete grid and
removing one cell at a time. Before a removal is accepted, a uniqueness
-checking solver (backtracking, early-exit at the 2nd solution found)
confirms exactly one solution remains. Removals that would create a
second solution are rejected and the cell is restored. This makes it
mathematically impossible for this script to emit an ambiguous puzzle.

Difficulty classification is by clue count.

Usage
-----
    # Classic 9×9 (default):
    python backend/scripts/gen_sudoku_puzzles.py \\
        --count 1000 \\
        --output frontend/src/game/sudoku/puzzles.json

    # Mini 6×6:
    python backend/scripts/gen_sudoku_puzzles.py \\
        --variant mini \\
        --count 1000 \\
        --output frontend/src/game/sudoku/puzzles_mini.json
"""

from __future__ import annotations

import argparse
import json
import random
import sys
import time
from pathlib import Path


# ---------------------------------------------------------------------------
# Grid representation — parameterised on (SIZE, BOX_ROWS, BOX_COLS)
# ---------------------------------------------------------------------------

def _make_peers(size: int, box_rows: int, box_cols: int) -> list[frozenset[int]]:
    """Pre-compute peer sets for all SIZE² cells."""
    total = size * size
    peers_list: list[frozenset[int]] = []
    for i in range(total):
        r, c = divmod(i, size)
        br, bc = r // box_rows, c // box_cols
        peers: set[int] = set()
        for j in range(total):
            if j == i:
                continue
            jr, jc = divmod(j, size)
            if jr == r or jc == c or (jr // box_rows == br and jc // box_cols == bc):
                peers.add(j)
        peers_list.append(frozenset(peers))
    return peers_list


def _candidates(grid: list[int], i: int, peers_list: list[frozenset[int]], size: int) -> int:
    """Return a SIZE-bit mask of digits not conflicting with peers of cell ``i``."""
    used = 0
    for p in peers_list[i]:
        v = grid[p]
        if v:
            used |= 1 << (v - 1)
    full = (1 << size) - 1
    return (~used) & full


def _pick_empty(
    grid: list[int], peers_list: list[frozenset[int]], size: int
) -> tuple[int, int]:
    """Return (index, candidate_mask) for empty cell with fewest candidates.
    Returns (-1, 0) when full. (MRV heuristic.)"""
    total = size * size
    best_i = -1
    best_mask = 0
    best_count = size + 1
    for i in range(total):
        if grid[i] == 0:
            mask = _candidates(grid, i, peers_list, size)
            cnt = bin(mask).count("1")
            if cnt < best_count:
                best_count = cnt
                best_i = i
                best_mask = mask
                if cnt <= 1:
                    break
    return best_i, best_mask


# ---------------------------------------------------------------------------
# Solver with early-exit solution counter
# ---------------------------------------------------------------------------


def count_solutions(
    grid: list[int],
    limit: int = 2,
    peers_list: list[frozenset[int]] | None = None,
    size: int = 9,
) -> int:
    """Count solutions up to ``limit``. Returns 0, 1, or ``limit``."""
    if peers_list is None:
        # Default to classic 9×9
        peers_list = _CLASSIC_PEERS
        size = 9
    counter = [0]
    work = list(grid)

    def recurse() -> None:
        if counter[0] >= limit:
            return
        i, mask = _pick_empty(work, peers_list, size)  # type: ignore[arg-type]
        if i == -1:
            counter[0] += 1
            return
        while mask:
            lsb = mask & -mask
            mask ^= lsb
            d = lsb.bit_length()
            work[i] = d
            recurse()
            work[i] = 0
            if counter[0] >= limit:
                return

    recurse()
    return counter[0]


def solve(
    grid: list[int],
    peers_list: list[frozenset[int]] | None = None,
    size: int = 9,
) -> list[int] | None:
    """Return a solved copy of ``grid``, or None if unsolvable."""
    if peers_list is None:
        peers_list = _CLASSIC_PEERS
        size = 9
    work = list(grid)

    def recurse() -> bool:
        i, mask = _pick_empty(work, peers_list, size)  # type: ignore[arg-type]
        if i == -1:
            return True
        while mask:
            lsb = mask & -mask
            mask ^= lsb
            d = lsb.bit_length()
            work[i] = d
            if recurse():
                return True
            work[i] = 0
        return False

    return work if recurse() else None


# ---------------------------------------------------------------------------
# Full grid generator
# ---------------------------------------------------------------------------


def random_full_grid(
    rng: random.Random,
    peers_list: list[frozenset[int]],
    size: int,
) -> list[int]:
    """Return a random complete valid grid."""
    total = size * size
    grid = [0] * total

    def recurse() -> bool:
        i, mask = _pick_empty(grid, peers_list, size)
        if i == -1:
            return True
        digits = []
        m = mask
        while m:
            lsb = m & -m
            m ^= lsb
            digits.append(lsb.bit_length())
        rng.shuffle(digits)
        for d in digits:
            grid[i] = d
            if recurse():
                return True
            grid[i] = 0
        return False

    recurse()
    return grid


# ---------------------------------------------------------------------------
# Hollowing (uniqueness-preserving removal loop)
# ---------------------------------------------------------------------------

TIER_RANGES: dict[str, tuple[int, int]] = {
    "easy": (36, 44),
    "medium": (28, 35),
    "hard": (22, 27),
}

TIER_RANGES_MINI: dict[str, tuple[int, int]] = {
    "easy": (14, 18),
    "medium": (11, 13),
    "hard": (8, 10),
}


def hollow(
    grid: list[int],
    target_clues: int,
    rng: random.Random,
    peers_list: list[frozenset[int]],
    size: int,
) -> list[int] | None:
    """Remove cells preserving unique solution until ``target_clues`` reached."""
    puzzle = list(grid)
    total = size * size
    order = list(range(total))
    rng.shuffle(order)
    current_clues = total

    for idx in order:
        if current_clues <= target_clues:
            break
        saved = puzzle[idx]
        if saved == 0:
            continue
        puzzle[idx] = 0
        if count_solutions(puzzle, 2, peers_list, size) == 1:
            current_clues -= 1
        else:
            puzzle[idx] = saved

    return puzzle


def classify(puzzle: list[int], tier_ranges: dict[str, tuple[int, int]]) -> str | None:
    clues = sum(1 for v in puzzle if v)
    for tier, (lo, hi) in tier_ranges.items():
        if lo <= clues <= hi:
            return tier
    return None


def puzzle_to_string(puzzle: list[int]) -> str:
    return "".join(str(v) for v in puzzle)


# ---------------------------------------------------------------------------
# Lazy-initialised classic peer list (kept for test_sudoku_puzzles backward compat)
# ---------------------------------------------------------------------------

_CLASSIC_PEERS: list[frozenset[int]] = _make_peers(9, 3, 3)


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------


def generate_bank(
    count_per_tier: int,
    size: int,
    box_rows: int,
    box_cols: int,
    tier_ranges: dict[str, tuple[int, int]],
    seed: int = 20260419,
) -> dict[str, list[str]]:
    rng = random.Random(seed)
    peers_list = _make_peers(size, box_rows, box_cols)
    banks: dict[str, list[str]] = {"easy": [], "medium": [], "hard": []}
    start = time.monotonic()
    attempts = 0

    while min(len(b) for b in banks.values()) < count_per_tier:
        attempts += 1
        grid = random_full_grid(rng, peers_list, size)

        need = {t: count_per_tier - len(banks[t]) for t in banks}
        tier = max(need, key=lambda t: need[t])
        lo, hi = tier_ranges[tier]
        target = rng.randint(lo, hi)

        puzzle = hollow(grid, target, rng, peers_list, size)
        if puzzle is None:
            continue
        resolved = classify(puzzle, tier_ranges)
        if resolved is None:
            continue
        if len(banks[resolved]) >= count_per_tier:
            continue

        banks[resolved].append(puzzle_to_string(puzzle))

        if attempts % 25 == 0:
            elapsed = time.monotonic() - start
            sizes = {t: len(banks[t]) for t in banks}
            total = sum(sizes.values())
            rate = total / elapsed if elapsed else 0
            print(
                f"[{elapsed:6.1f}s] attempts={attempts} sizes={sizes} rate={rate:.2f}/s",
                file=sys.stderr,
            )

    elapsed = time.monotonic() - start
    print(
        f"Done. attempts={attempts} elapsed={elapsed:.1f}s sizes="
        f"{ {t: len(b) for t, b in banks.items()} }",
        file=sys.stderr,
    )
    return banks


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate Sudoku puzzle bank.")
    ap.add_argument("--count", type=int, default=1000, help="puzzles per difficulty")
    ap.add_argument("--seed", type=int, default=20260419)
    ap.add_argument("--variant", choices=["classic", "mini"], default="classic")
    ap.add_argument(
        "--output",
        default=None,
    )
    args = ap.parse_args()

    _FRONTEND = Path(__file__).resolve().parents[2] / "frontend" / "src" / "game" / "sudoku"

    if args.variant == "mini":
        size, box_rows, box_cols = 6, 2, 3
        tier_ranges = TIER_RANGES_MINI
        default_output = str(_FRONTEND / "puzzles_mini.json")
    else:
        size, box_rows, box_cols = 9, 3, 3
        tier_ranges = TIER_RANGES
        default_output = str(_FRONTEND / "puzzles.json")

    out_path = Path(args.output or default_output)

    banks = generate_bank(args.count, size, box_rows, box_cols, tier_ranges, args.seed)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(banks, indent=2) + "\n")
    print(f"Wrote {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
