/**
 * Sudoku engine (#616) — pure functions over an immutable `SudokuState`.
 *
 * No React, no AsyncStorage, no side effects. The UI and persistence
 * layers consume the returned state verbatim.
 *
 * Solvability guarantee: puzzles in `puzzles.json` were generated by
 * `backend/scripts/gen_sudoku_puzzles.py` with a uniqueness-checking
 * backtracking solver — every puzzle has exactly one solution. This
 * module trusts that invariant and uses `solvePuzzle` at load time to
 * derive the single solution string for error-checking.
 */

import puzzleBank from "./puzzles.json";
import type { CellValue, Difficulty, Grid, NoteDigit, SudokuCell, SudokuState } from "./types";
import { UNDO_STACK_LIMIT } from "./types";

// ---------------------------------------------------------------------------
// Solver — backtracking with candidate bitmasks
// ---------------------------------------------------------------------------

/** Bitmask of digits used by peers of cell `i` in `grid`. */
function peerMask(grid: Int8Array, i: number): number {
  const r = Math.floor(i / 9);
  const c = i % 9;
  const br = Math.floor(r / 3) * 3;
  const bc = Math.floor(c / 3) * 3;
  let used = 0;
  for (let k = 0; k < 9; k++) {
    const rowCell = grid[r * 9 + k];
    if (rowCell) used |= 1 << (rowCell - 1);
    const colCell = grid[k * 9 + c];
    if (colCell) used |= 1 << (colCell - 1);
  }
  for (let rr = 0; rr < 3; rr++) {
    for (let cc = 0; cc < 3; cc++) {
      const v = grid[(br + rr) * 9 + (bc + cc)];
      if (v) used |= 1 << (v - 1);
    }
  }
  return ~used & 0x1ff;
}

/** MRV: return index of empty cell with fewest candidates, or -1 if full. */
function pickEmpty(grid: Int8Array): { i: number; mask: number } {
  let bestI = -1;
  let bestMask = 0;
  let bestCount = 10;
  for (let i = 0; i < 81; i++) {
    if (grid[i] === 0) {
      const m = peerMask(grid, i);
      // popcount for 9-bit mask
      let c = m;
      c = c - ((c >> 1) & 0x55);
      c = (c & 0x33) + ((c >> 2) & 0x33);
      const count = (((c + (c >> 4)) & 0x0f) * 0x01) & 0xff;
      if (count < bestCount) {
        bestCount = count;
        bestI = i;
        bestMask = m;
        if (count <= 1) break;
      }
    }
  }
  return { i: bestI, mask: bestMask };
}

/** Solve `puzzle` (81-char string, '0' for empty) and return the solved
 * 81-char string, or null if the puzzle has no solution. */
export function solvePuzzle(puzzle: string): string | null {
  if (puzzle.length !== 81) return null;
  const grid = new Int8Array(81);
  for (let i = 0; i < 81; i++) {
    const ch = puzzle.charCodeAt(i) - 48;
    if (ch < 0 || ch > 9) return null;
    grid[i] = ch;
  }

  // Validate the givens — the backtracker only checks peer conflicts
  // for *new* placements, so a starting grid with two of a digit in the
  // same unit would send it into exponential futility.  Reject up front.
  for (let i = 0; i < 81; i++) {
    const v = grid[i];
    if (!v) continue;
    grid[i] = 0;
    const mask = peerMask(grid, i);
    grid[i] = v;
    if ((mask & (1 << (v - 1))) === 0) return null;
  }

  const recurse = (): boolean => {
    const { i, mask } = pickEmpty(grid);
    if (i === -1) return true;
    if (mask === 0) return false;
    let m = mask;
    while (m) {
      const lsb = m & -m;
      m ^= lsb;
      const d = Math.log2(lsb) + 1;
      grid[i] = d;
      if (recurse()) return true;
      grid[i] = 0;
    }
    return false;
  };

  if (!recurse()) return null;
  let out = "";
  for (let i = 0; i < 81; i++) out += grid[i];
  return out;
}

// ---------------------------------------------------------------------------
// Grid construction
// ---------------------------------------------------------------------------

function makeCell(value: CellValue, given: boolean): SudokuCell {
  return {
    value,
    given,
    notes: new Set<NoteDigit>(),
    isError: false,
  };
}

function buildGrid(puzzle: string): Grid {
  const rows: SudokuCell[][] = [];
  for (let r = 0; r < 9; r++) {
    const row: SudokuCell[] = [];
    for (let c = 0; c < 9; c++) {
      const ch = puzzle.charCodeAt(r * 9 + c) - 48;
      const v = (ch >= 0 && ch <= 9 ? ch : 0) as CellValue;
      row.push(makeCell(v, v !== 0));
    }
    rows.push(row);
  }
  return rows;
}

function cellAt(grid: Grid, row: number, col: number): SudokuCell {
  const r = grid[row];
  if (!r) throw new Error(`row out of range: ${row}`);
  const cell = r[col];
  if (!cell) throw new Error(`col out of range: ${col}`);
  return cell;
}

function replaceCell(
  grid: Grid,
  row: number,
  col: number,
  updater: (cell: SudokuCell) => SudokuCell
): Grid {
  return grid.map((r, ri) =>
    ri === row ? r.map((cell, ci) => (ci === col ? updater(cell) : cell)) : r
  );
}

/** Apply `updater` to every cell — used when peer notes need clearing. */
function mapGrid(
  grid: Grid,
  updater: (cell: SudokuCell, row: number, col: number) => SudokuCell
): Grid {
  return grid.map((r, ri) => r.map((cell, ci) => updater(cell, ri, ci)));
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

type PuzzleBank = Record<Difficulty, readonly string[]>;
const BANK = puzzleBank as PuzzleBank;

/** Pick a random puzzle of the given difficulty and build a fresh state. */
export function loadPuzzle(difficulty: Difficulty, rng: () => number = Math.random): SudokuState {
  const pool = BANK[difficulty];
  if (!pool || pool.length === 0) {
    throw new Error(`No puzzles available for difficulty: ${difficulty}`);
  }
  const idx = Math.floor(rng() * pool.length);
  const puzzle = pool[idx];
  if (!puzzle) throw new Error(`puzzle index ${idx} missing`);
  const solution = solvePuzzle(puzzle);
  if (!solution) {
    throw new Error(`Unsolvable puzzle in bank at ${difficulty}[${idx}]`);
  }
  return {
    _v: 1,
    difficulty,
    puzzle,
    solution,
    grid: buildGrid(puzzle),
    selectedRow: null,
    selectedCol: null,
    notesMode: false,
    errorCount: 0,
    isComplete: false,
    undoStack: [],
  };
}

/** Select a cell. Selecting the already-selected cell deselects it. */
export function selectCell(state: SudokuState, row: number, col: number): SudokuState {
  if (state.selectedRow === row && state.selectedCol === col) {
    return { ...state, selectedRow: null, selectedCol: null };
  }
  return { ...state, selectedRow: row, selectedCol: col };
}

export function toggleNotesMode(state: SudokuState): SudokuState {
  return { ...state, notesMode: !state.notesMode };
}

function pushUndo(state: SudokuState): readonly SudokuState[] {
  // The snapshot stored in the stack never holds its own undoStack — that
  // would cause exponential nesting as moves accumulate.  Callers reading
  // the stack must treat those snapshots as terminal ("no deeper history").
  const snapshot: SudokuState = { ...state, undoStack: [] };
  const next = [...state.undoStack, snapshot];
  return next.length > UNDO_STACK_LIMIT ? next.slice(next.length - UNDO_STACK_LIMIT) : next;
}

function isGridComplete(grid: Grid, solution: string): boolean {
  for (let r = 0; r < 9; r++) {
    for (let c = 0; c < 9; c++) {
      const cell = cellAt(grid, r, c);
      if (cell.value === 0) return false;
      const expected = solution.charCodeAt(r * 9 + c) - 48;
      if (cell.value !== expected) return false;
    }
  }
  return true;
}

/** Alias exported so tests (and downstream UI) can ask the question
 * without reaching into the `state.isComplete` field directly. */
export function isComplete(grid: Grid, solution: string): boolean {
  return isGridComplete(grid, solution);
}

/** Enter a digit into the selected cell.
 *
 * Normal mode (`notesMode === false`):
 *   - Sets `cell.value = digit`
 *   - Clears the cell's pencil notes
 *   - Flags `isError` when the placed digit disagrees with the solution;
 *     increments `errorCount` in that case
 *   - Pushes the previous state to the undo stack (capped at
 *     UNDO_STACK_LIMIT)
 *   - Checks for completion
 *
 * Notes mode (`notesMode === true`):
 *   - Toggles the digit in the cell's notes set
 *   - Does NOT affect `cell.value`, `errorCount`, or completion
 *   - Does NOT push to the undo stack (notes are free to experiment with)
 *   - If a digit is added to notes, it's first removed from the notes of
 *     any peer that already has that digit as a *confirmed* value
 *     (nothing to do because such a note can't legally be there, but the
 *     issue called it out — we keep the peer-clearing pass for
 *     robustness against externally-produced states).
 *
 * No-op when nothing is selected or the selected cell is a given. */
export function enterDigit(state: SudokuState, digit: CellValue): SudokuState {
  if (state.selectedRow === null || state.selectedCol === null) return state;
  const row = state.selectedRow;
  const col = state.selectedCol;
  const cell = cellAt(state.grid, row, col);
  if (cell.given) return state;
  if (digit === 0) return state;

  if (state.notesMode) {
    const d = digit as NoteDigit;
    const nextNotes = new Set(cell.notes);
    if (nextNotes.has(d)) nextNotes.delete(d);
    else nextNotes.add(d);
    // Peer-clearing sweep: a digit being noted in (row, col) must not
    // remain as a note in any peer that holds that digit as a
    // *confirmed* value.  In practice notes are only added when the
    // confirmed value isn't in the cell, so this is defensive.
    const nextGrid = mapGrid(state.grid, (c, ri, ci) => {
      if (ri === row && ci === col) {
        return { ...c, notes: nextNotes };
      }
      if (!peers(row, col, ri, ci)) return c;
      if (c.value === d && c.notes.has(d)) {
        const trimmed = new Set(c.notes);
        trimmed.delete(d);
        return { ...c, notes: trimmed };
      }
      return c;
    });
    return { ...state, grid: nextGrid };
  }

  // Normal mode.
  const undoStack = pushUndo(state);
  const expected = state.solution.charCodeAt(row * 9 + col) - 48;
  const isError = digit !== expected;
  const nextGrid = replaceCell(state.grid, row, col, (c) => ({
    ...c,
    value: digit,
    notes: new Set<NoteDigit>(),
    isError,
  }));
  const nextErrorCount = isError ? state.errorCount + 1 : state.errorCount;
  return {
    ...state,
    grid: nextGrid,
    errorCount: nextErrorCount,
    isComplete: isGridComplete(nextGrid, state.solution),
    undoStack,
  };
}

/** Clear the value AND notes of the selected cell. No-op on given cells
 * or when nothing is selected. Pushes to the undo stack. */
export function eraseCell(state: SudokuState): SudokuState {
  if (state.selectedRow === null || state.selectedCol === null) return state;
  const row = state.selectedRow;
  const col = state.selectedCol;
  const cell = cellAt(state.grid, row, col);
  if (cell.given) return state;
  if (cell.value === 0 && cell.notes.size === 0) return state;
  const undoStack = pushUndo(state);
  const nextGrid = replaceCell(state.grid, row, col, (c) => ({
    ...c,
    value: 0,
    notes: new Set<NoteDigit>(),
    isError: false,
  }));
  return {
    ...state,
    grid: nextGrid,
    isComplete: false,
    undoStack,
  };
}

/** Pop the most recent undo snapshot. Returns the current state if the
 * stack is empty. The popped snapshot is the state *before* the last
 * move — it carries its own (nested-empty) undo stack, which we re-
 * thread with the caller's now-shortened history so subsequent undos
 * continue walking backwards. */
export function undo(state: SudokuState): SudokuState {
  if (state.undoStack.length === 0) return state;
  const prev = state.undoStack[state.undoStack.length - 1];
  if (!prev) return state;
  return {
    ...prev,
    undoStack: state.undoStack.slice(0, -1),
  };
}

// ---------------------------------------------------------------------------
// Helpers for UI / error flash
// ---------------------------------------------------------------------------

function peers(r1: number, c1: number, r2: number, c2: number): boolean {
  if (r1 === r2 && c1 === c2) return false;
  if (r1 === r2 || c1 === c2) return true;
  return Math.floor(r1 / 3) === Math.floor(r2 / 3) && Math.floor(c1 / 3) === Math.floor(c2 / 3);
}

/** Return the coordinates of all cells that already hold `value` in the
 * same row, column, or 3×3 box as (`row`, `col`). Used by the UI to
 * flash conflicts when the player places a colliding digit. */
export function getConflicts(
  grid: Grid,
  row: number,
  col: number,
  value: number
): Array<[number, number]> {
  if (value < 1 || value > 9) return [];
  const out: Array<[number, number]> = [];
  for (let r = 0; r < 9; r++) {
    for (let c = 0; c < 9; c++) {
      if (r === row && c === col) continue;
      if (!peers(row, col, r, c)) continue;
      const cell = cellAt(grid, r, c);
      if (cell.value === value) out.push([r, c]);
    }
  }
  return out;
}
