// Static require map for all 42 mahjong tile SVGs (faceId 1–42).
// Metro resolves require() at bundle time — paths must be static literals.
// Index 0 = faceId 1 (white dragon) … index 41 = faceId 42 (bamboo flower).
/* eslint-disable @typescript-eslint/no-require-imports */
export const TILE_REQUIRES: readonly number[] = [
  require("../../../assets/mahjong/01-white-dragon.svg"),
  require("../../../assets/mahjong/02-green-dragon.svg"),
  require("../../../assets/mahjong/03-red-dragon.svg"),
  require("../../../assets/mahjong/04-east-wind.svg"),
  require("../../../assets/mahjong/05-south-wind.svg"),
  require("../../../assets/mahjong/06-west-wind.svg"),
  require("../../../assets/mahjong/07-north-wind.svg"),
  require("../../../assets/mahjong/08-characters-1.svg"),
  require("../../../assets/mahjong/09-characters-2.svg"),
  require("../../../assets/mahjong/10-characters-3.svg"),
  require("../../../assets/mahjong/11-characters-4.svg"),
  require("../../../assets/mahjong/12-characters-5.svg"),
  require("../../../assets/mahjong/13-characters-6.svg"),
  require("../../../assets/mahjong/14-characters-7.svg"),
  require("../../../assets/mahjong/15-characters-8.svg"),
  require("../../../assets/mahjong/16-characters-9.svg"),
  require("../../../assets/mahjong/17-circles-1.svg"),
  require("../../../assets/mahjong/18-circles-2.svg"),
  require("../../../assets/mahjong/19-circles-3.svg"),
  require("../../../assets/mahjong/20-circles-4.svg"),
  require("../../../assets/mahjong/21-circles-5.svg"),
  require("../../../assets/mahjong/22-circles-6.svg"),
  require("../../../assets/mahjong/23-circles-7.svg"),
  require("../../../assets/mahjong/24-circles-8.svg"),
  require("../../../assets/mahjong/25-circles-9.svg"),
  require("../../../assets/mahjong/26-bamboos-1.svg"),
  require("../../../assets/mahjong/27-bamboos-2.svg"),
  require("../../../assets/mahjong/28-bamboos-3.svg"),
  require("../../../assets/mahjong/29-bamboos-4.svg"),
  require("../../../assets/mahjong/30-bamboos-5.svg"),
  require("../../../assets/mahjong/31-bamboos-6.svg"),
  require("../../../assets/mahjong/32-bamboos-7.svg"),
  require("../../../assets/mahjong/33-bamboos-8.svg"),
  require("../../../assets/mahjong/34-bamboos-9.svg"),
  require("../../../assets/mahjong/35-spring.svg"),
  require("../../../assets/mahjong/36-summer.svg"),
  require("../../../assets/mahjong/37-autumn.svg"),
  require("../../../assets/mahjong/38-winter.svg"),
  require("../../../assets/mahjong/39-plum.svg"),
  require("../../../assets/mahjong/40-orchid.svg"),
  require("../../../assets/mahjong/41-chrysanthemum.svg"),
  require("../../../assets/mahjong/42-bamboo.svg"),
];
/* eslint-enable @typescript-eslint/no-require-imports */
