name: CI

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]
  workflow_call:
    secrets: inherit

jobs:
  gate-main-source:
    uses: wcmchenry3-stack/.github/.github/workflows/called-gate-main-source.yml@main
    secrets: inherit

  secret-scan:
    uses: wcmchenry3-stack/.github/.github/workflows/called-secret-scan.yml@main
    secrets: inherit

  lint-python:
    uses: wcmchenry3-stack/.github/.github/workflows/called-lint-python.yml@main
    with:
      working-directory: backend
    secrets: inherit

  lint-frontend:
    uses: wcmchenry3-stack/.github/.github/workflows/called-lint-frontend.yml@main
    with:
      working-directory: frontend
    secrets: inherit

  test-python:
    uses: wcmchenry3-stack/.github/.github/workflows/called-test-python.yml@main
    with:
      working-directory: backend
    secrets: inherit

  test-frontend:
    uses: wcmchenry3-stack/.github/.github/workflows/called-test-frontend.yml@main
    with:
      working-directory: frontend
    secrets: inherit

  cve-python:
    uses: wcmchenry3-stack/.github/.github/workflows/called-cve-python.yml@main
    with:
      working-directory: backend
    secrets: inherit

  cve-frontend:
    uses: wcmchenry3-stack/.github/.github/workflows/called-cve-frontend.yml@main
    with:
      working-directory: frontend
    secrets: inherit
