name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: wcmchenry3-stack/.github/.github/workflows/called-release-please.yml@main
